#!/bin/sh
#
#  Wrapper script for SLURM2.1+ job submission
#
qsubout=.qsub$$
qsubin=.qsubin$$

HOST=`hostname`
PATH=$PATH:/usr/bin:/bin:/usr/sbin:/usr/bsd:/usr/local/bin

# Get QPATH and QSUB settings from the config file
curdir=`echo "$0" | sed -e 's#/[^/]*$##'`
if [ -f "$curdir/config" ]; then
  . "$curdir/config"
else
  echo "ERROR: The $curdir/config file is missing."
  exit 1
fi

if [ -n "$QPROFILE" ]; then
  if [ -f "$QPROFILE" ]; then
    . "$QPROFILE"
  else 
    echo "ERROR: Setup script \"$QPROFILE\" not found."
    exit 1
  fi
fi 

if [ -n "$QPATH" ]; then
  PATH=$QPATH:$PATH
fi

# Verify commandline args
if [ $# -gt 0 ]; then
  script="$1"
  shift
else
  echo "ERROR: Usage:   submit <script> [<options>]"
  exit 1
fi

ARGS=""
QLOG=""
LICENSE_ARGS=""
while [ $# -gt 0 ]; do
  case "$1" in
    -lic) LICENSE_ARGS="$LICENSE_ARGS -l $2"
          shift 2 ;;
      -o) QLOG="$2"
          shift 2 ;;
       *) ARGS="$ARGS \"$1\"" 
          shift ;;
  esac
done

if [ -n "$QLOG" ]; then
  touch "$QLOG" 2>&- || QLOG="/dev/null"
  ARGS="$ARGS -o '$QLOG'"
fi

if [ -z "$LICENSE_CHECKING" ]; then
  LICENSE_ARGS=""
else
  echo "ERROR: License checking is not yet supported for SLURM"
  echo "ERROR: Set LICENSE_CHECKING='' in your SLURM/config file"
  echo "ERROR: to avoid getting this message."
  exit 1
fi
  
if [ "$script" != "-" -a ! -f "$script" ]; then
  echo "ERROR: File not found: \"$script\""
  exit 1
fi

if [ -z "`which $QSUB 2>/dev/null`" -a ! -x "$QPATH/$QSUB" -a ! -x "$QSUB" ]; then
  echo "ERROR: Submission command \"$QSUB\" on host \"$HOST\" not found."
  echo "ERROR: (i) Is the Host: field in your schrodinger.hosts entry correct?"
  echo "ERROR: (ii) Are the QPATH and QSUB settings in $curdir/config correct?"
  exit 1
fi

# Submit job
if [ "$script" = "-" ]; then
  # As of SLURM v2.2, sbatch still does not seem to properly take input on stdin
  cat > $qsubin
  script=$qsubin
fi

#UPDATE: For slurm 2.1.0-1 (ubuntu 10.04 release submit info is returned on <stdout>
echo ">> $QSUB $QARGS $ARGS $LICENSE_ARGS \"$script\" 1> $qsubout < /dev/null"
eval $QSUB $QARGS $ARGS $LICENSE_ARGS \"$script\" 1> $qsubout < /dev/null

if [ $? = 0 ]; then
    # Parse job id from output "your job <jobid> ... has been submitted" 
    #UPDATE: For slurm 2.1.0-1 (ubuntu 10.04 release) output is "Submitted batch job <jobid>"
    batchid=`head -1 $qsubout | awk '{print $4}'`
    if [ -n "$batchid" ]; then
        echo "BatchId: $batchid"
        rm $qsubout
        rm $qsubin 2> /dev/null
        exit 0
    fi
fi

# Job submission apparently failed
cat $qsubout | sed 's/\(.*\)/ERROR: \1/'
rm $qsubout
rm $qsubin 2> /dev/null
exit 1
